algoritmo "Trabalhando com Tipos"

var
   palavra1, palavra2, palavra3: literal
   numero1, numero2, numero3: inteiro
   
inicio
      Escreval("Palavra1: ")
      leia(palavra1)
      Escreval ("Palavra2: ")
      leia(palavra2)
      Escreval("Número1: ")
      leia(numero1)
      Escreval("Número2: ")
      leia(numero2)
      palavra3 <- palavra1 + palavra2
      numero3 <- numero1 + numero2
      Escreval(palavra3)
      Escreval (numero3)

fimalgoritmo
