algoritmo "PARA - ALEATORIO"

var
// AMax - Aleatório Máximo
// AMin - Aleatório Mínimo
// P - Passo

i, AMax, Amin, P: inteiro

inicio

REPITA
ALEATORIO 1,100
          leia(AMax)
          leia(Amin)
ALEATORIO OFF
ATE AMax > AMin
limpatela

ALEATORIO 1, 5
          Leia(P)
ALEATORIO OFF
limpatela

PARA i de AMin ate AMax passo P FACA
          escreval(i)
FIMPARA

fimalgoritmo
