algoritmo "Operador Escolha"

var

voto: literal

inicio

Escreval("Digite o seu voto: ")
leia(voto)

Escolha voto
caso "10"
      Escreval("Você votou no Zero.")
caso "20"
      Escreval("Você votou no Jaspion.")
caso "30"
      Escreval("Você votou no Pernalonga.")
caso "40"
      Escreval("Você votou no Zé da Manga.")
caso "50"
      Escreval("Você votou no Papa-Léguas.")
Outrocaso
      Escreval("Você votou nulo.")
Fimescolha
             
fimalgoritmo
